# Generated by Django 5.1.3 on 2025-05-21 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_num', models.CharField(editable=False, max_length=20, unique=True)),
                ('ident', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=100)),
                ('length', models.DecimalField(decimal_places=4, max_digits=10)),
                ('width', models.DecimalField(decimal_places=4, max_digits=10)),
                ('depth', models.DecimalField(decimal_places=4, max_digits=10)),
                ('blank_size', models.CharField(max_length=100)),
                ('test', models.CharField(max_length=100)),
                ('flute', models.CharField(max_length=100)),
                ('paper', models.TextField()),
                ('ard_required', models.BooleanField(default=False)),
                ('pdf_required', models.BooleanField(default=False)),
                ('eps_required', models.BooleanField(default=False)),
                ('dxf_required', models.BooleanField(default=False)),
                ('cape_required', models.BooleanField(default=False)),
                ('samples_required', models.BooleanField(default=False)),
                ('num_samples_requested', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('p', 'Pending'), ('a', 'Assigned'), ('i', 'In Progress'), ('s', 'Sent'), ('a', 'Approved'), ('o', 'Ordered')], default='p', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_designs', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_designs', to='customers.customer')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_designs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DesignAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='design_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='designs.design')),
            ],
        ),
    ]
