# Generated by Django 5.2.1 on 2025-05-22 17:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_remove_design_assigned_to_remove_design_requested_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='status_updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
