# Generated by Django 5.2.1 on 2025-05-22 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0006_alter_design_design_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='parent_design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='designs.design'),
        ),
        migrations.AddField(
            model_name='design',
            name='revision_letter',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
