# Generated by Django 5.2.1 on 2025-05-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0007_design_parent_design_design_revision_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('as', 'Assigned'), ('ip', 'In Progress'), ('s', 'Sent'), ('ap', 'Approved'), ('o', 'Ordered')], default='p', max_length=20),
        ),
    ]
