# Generated by Django 5.2.1 on 2025-05-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0008_alter_design_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='blank_size',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
