# Generated by Django 5.2.1 on 2025-05-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0009_alter_design_blank_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='design_num_index',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
