# Generated by Django 5.2.1 on 2025-05-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0010_design_design_num_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designattachment',
            name='file',
            field=models.FileField(upload_to='designs/design_attachments/'),
        ),
    ]
