# Generated by Django 5.2.1 on 2025-07-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0011_alter_designattachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='depth',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='design',
            name='length',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='design',
            name='width',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
